version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./next
      dockerfile: Dockerfile
      target: production
      args:
        - HOST_API=http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next
    environment:
      - NODE_ENV=production
    env_file:
      - next/.env

    depends_on:
      - agentgpt_db
  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: agentgpt_db
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
      REWORKD_PLATFORM_DB_CA_PATH: "db/db_data/ca.pem"
      DATABASE_URL: "mysql://reworkd_platform:reworkd_platform@agentgpt_db:3307/reworkd_platform"
      NEXTAUTH_SECRET: rKoAN2ZhCcG5tJ/Z2R9ztahGos3JARFW0B7Kt57S+I8=
      NEXTAUTH_URL: http://localhost:3000
      SQLLite: file:./db.sqlite

    depends_on:
      - agentgpt_db

  agentgpt_db:
    image: mysql:8.0
    container_name: agentgpt_db
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./db
    ports:
      - "3308:3307"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password


    volumes:
      - agentgpt_db:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  agentgpt_db:


secrets:
  db_password:
    file: .secrets/db_password.txt
  db_root_password:
    file: .secrets/db_root_password.txt
