apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-chat-app
  namespace: agent-chat
  labels:
    app: agent-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-chat-app
  template:
    metadata:
      labels:
        app: agent-chat-app
    spec:
      containers:
        - name: agent-chat-app
          image: docker.io/<docker-username>/agent-chat-app:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: k8s-secret
            - configMapRef:
                name: app-config
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
          volumeMounts:
            - name: config-volume
              readOnly: false
              mountPath: "/etc/config-volume"
            - name: secret-volume
              readOnly: false
              mountPath: "/etc/secret-volume"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: app-config
        - name: secret-volume
          secret:
            secretName: k8s-secret

